credit_default:
  target: ci
  outputs:
    ci:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      database: CREDIT_DEFAULT
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      schema: MODEL
      client_session_keep_alive: false
